
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Mar 20 15:05:56 EDT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A5Sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int READ = 19;
  public static final int ELSE = 17;
  public static final int SEMICOLON = 11;
  public static final int CP = 10;
  public static final int PLUS = 5;
  public static final int INT = 24;
  public static final int EQUAL = 14;
  public static final int NOTEQUAL = 15;
  public static final int OP = 9;
  public static final int END = 22;
  public static final int RETURN = 20;
  public static final int IF = 16;
  public static final int WRITE = 18;
  public static final int ID = 2;
  public static final int NUM = 3;
  public static final int BEGIN = 21;
  public static final int QUOTE = 4;
  public static final int STRING = 26;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int DIVIDE = 8;
  public static final int MAIN = 23;
  public static final int MINUS = 6;
  public static final int error = 1;
  public static final int ASSIGN = 13;
  public static final int REAL = 25;
}

